Feat: open files with relative path
makeworld-the-better-one/amfora pull request #232
Opened 2021-05-01 08:51 UTC by singalhimanshu

Now we can open files directly by running `amfora file.gmi` rather than
doing `amfora file:///absolute/path/to/file.gmi`

Solve #231

2021-05-07 02:34 UTC, makeworld-the-better-one requested changes
Thanks for making this PR.

Checking for specific protocols as you have done will not work. For example, you have missed `https://`. But more importantly, the user could be using any protocol at all, thanks to the features Amfora has like [proxying](https://github.com/makeworld-the-better-one/amfora/wiki/Proxying).

A better solution is to check for `://`. If that's missing, then check if the file exists, just passing the argument as is. Absolute or relative paths can be handled the same, and so it doesn't need to be checked for that. If the file exists, convert to a `file://` URL and pass it along. If the file doesn't exist, pass it along unchanged, as it's maybe a domain like `geminispace.info`.

Let me know when you've made these changes (by comment or requesting a review), and I'll take a look again.

2021-05-26 12:11 UTC, singalhimanshu commented
Sorry for the delay I couldn't get any spare time. This might take some time if that is okay.

2021-05-26 20:38 UTC, makeworld-the-better-one commented
No worries. Just let me know if you can't continue with this later for whatever reason, and I can take it over.

2021-12-08 00:30 UTC, makeworld-the-better-one commented
Fixed by #257. Thanks for your work though!

2021-12-08 00:30 UTC, closed without merging